spring:
  datasource:
    url: jdbc:mariadb://j5zntocs2dn6c3fj.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/zi4rcgvo4lslezx1
    username: j5hk61xjp8fio8vm
    password: g7uvhh97e0yb9cd8
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate.ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: office.learningscorecard@gmail.com
    password: LearningScorecard123
    properties.mail.smtp:
      auth: true
      starttls.enable: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

ls:
  auth:
    security:
      secret: 2ae0397612084557a0d946a6bb05fb6e
      jwtExpirationMs: 86400000